config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root to: "home#index"
  resources :buses
  resources :rings
  devise_for :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bus.rb
class Bus < ApplicationRecord
    after_create :balanco
    
    
    def balanco
        self.power_balance = self.maximum_transmission_power + self.baud_rate 
        self.save
    end
    #put

end

app/models/ring.rb
class Ring < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_student!

  layout 'admin_lte_2'

end

app/controllers/buses_controller.rb
class BusesController < ApplicationController
  before_action :set_bus, only: [:show, :edit, :update, :destroy]

  # GET /buses
  # GET /buses.json
  def index
    @buses = Bus.all
  end

  # GET /buses/1
  # GET /buses/1.json
  def show
  end

  # GET /buses/new
  def new
    @bus = Bus.new
  end

  # GET /buses/1/edit
  def edit
  end

  # POST /buses
  # POST /buses.json
  def create
    @bus = Bus.new(bus_params)

    respond_to do |format|
      if @bus.save
        format.html { redirect_to @bus, notice: 'Bus was successfully created.' }
        format.json { render :show, status: :created, location: @bus }
      else
        format.html { render :new }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buses/1
  # PATCH/PUT /buses/1.json
  def update
    respond_to do |format|
      if @bus.update(bus_params)
        format.html { redirect_to @bus, notice: 'Bus was successfully updated.' }
        format.json { render :show, status: :ok, location: @bus }
      else
        format.html { render :edit }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buses/1
  # DELETE /buses/1.json
  def destroy
    @bus.destroy
    respond_to do |format|
      format.html { redirect_to buses_url, notice: 'Bus was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bus
      @bus = Bus.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bus_params
      params.require(:bus).permit(:maximum_transmission_power, :baud_rate, :receiver_sensitivity, :effective_receiver_band, :codification, :link_distance, :number_of_stations, :insertion_loss, :loss_of_DP_coupling, :loss_of_excess_DP, :link_length, :fiber_attenuation_coefficient, :loss_of_transmission_of_the_T_coupler, :loss_of_coupling_T_coupler, :excess_loss_of_T_coupler, :dispersion_balance, :electric_Tx_bandwidth, :spectral_width, :chromatic_dispersion, :optical_bandwidth, :coupling_coefficient, :electric_Rx_bandwidth)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rings_controller.rb
class RingsController < ApplicationController
  before_action :set_ring, only: [:show, :edit, :update, :destroy]

  # GET /rings
  # GET /rings.json
  def index
    @rings = Ring.all
  end

  # GET /rings/1
  # GET /rings/1.json
  def show
  end

  # GET /rings/new
  def new
    @ring = Ring.new
  end

  # GET /rings/1/edit
  def edit
  end

  # POST /rings
  # POST /rings.json
  def create
    @ring = Ring.new(ring_params)

    respond_to do |format|
      if @ring.save
        format.html { redirect_to @ring, notice: 'Ring was successfully created.' }
        format.json { render :show, status: :created, location: @ring }
      else
        format.html { render :new }
        format.json { render json: @ring.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rings/1
  # PATCH/PUT /rings/1.json
  def update
    respond_to do |format|
      if @ring.update(ring_params)
        format.html { redirect_to @ring, notice: 'Ring was successfully updated.' }
        format.json { render :show, status: :ok, location: @ring }
      else
        format.html { render :edit }
        format.json { render json: @ring.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rings/1
  # DELETE /rings/1.json
  def destroy
    @ring.destroy
    respond_to do |format|
      format.html { redirect_to rings_url, notice: 'Ring was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ring
      @ring = Ring.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ring_params
      params.require(:ring).permit(:maximum_transmission_power, :baud_rate, :receiver_sensitivity, :effective_receiver_band, :codification, :link_distance)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buses_helper.rb
module BusesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rings_helper.rb
module RingsHelper
end

app/views/buses/_form.html.erb
<%= form_with(model: bus, local: true) do |form| %>
  <% if bus.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bus.errors.count, "error") %> prohibited this bus from being saved:</h2>

      <ul>
      <% bus.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :maximum_transmission_power %>
    <%= form.text_field :maximum_transmission_power %>
  </div>

  <div class="field">
    <%= form.label :baud_rate %>
    <%= form.text_field :baud_rate %>
  </div>

  <div class="field">
    <%= form.label :receiver_sensitivity %>
    <%= form.text_field :receiver_sensitivity %>
  </div>

  <div class="field">
    <%= form.label :effective_receiver_band %>
    <%= form.text_field :effective_receiver_band %>
  </div>

  <div class="field">
    <%= form.label :codification %>
    <%= form.check_box :codification %>
  </div>

  <div class="field">
    <%= form.label :link_distance %>
    <%= form.check_box :link_distance %>
  </div>

  <div class="field">
    <%= form.label :number_of_stations %>
    <%= form.text_field :number_of_stations %>
  </div>

  <div class="field">
    <%= form.label :insertion_loss %>
    <%= form.text_field :insertion_loss %>
  </div>

  <div class="field">
    <%= form.label :loss_of_DP_coupling %>
    <%= form.text_field :loss_of_DP_coupling %>
  </div>

  <div class="field">
    <%= form.label :loss_of_excess_DP %>
    <%= form.text_field :loss_of_excess_DP %>
  </div>

  <div class="field">
    <%= form.label :link_length %>
    <%= form.text_field :link_length %>
  </div>

  <div class="field">
    <%= form.label :fiber_attenuation_coefficient %>
    <%= form.text_field :fiber_attenuation_coefficient %>
  </div>

  <div class="field">
    <%= form.label :loss_of_transmission_of_the_T_coupler %>
    <%= form.text_field :loss_of_transmission_of_the_T_coupler %>
  </div>

  <div class="field">
    <%= form.label :loss_of_coupling_T_coupler %>
    <%= form.text_field :loss_of_coupling_T_coupler %>
  </div>

  <div class="field">
    <%= form.label :excess_loss_of_T_coupler %>
    <%= form.text_field :excess_loss_of_T_coupler %>
  </div>

  <div class="field">
    <%= form.label :dispersion_balance %>
    <%= form.text_field :dispersion_balance %>
  </div>

  <div class="field">
    <%= form.label :electric_Tx_bandwidth %>
    <%= form.text_field :electric_Tx_bandwidth %>
  </div>

  <div class="field">
    <%= form.label :spectral_width %>
    <%= form.text_field :spectral_width %>
  </div>

  <div class="field">
    <%= form.label :chromatic_dispersion %>
    <%= form.text_field :chromatic_dispersion %>
  </div>

  <div class="field">
    <%= form.label :optical_bandwidth %>
    <%= form.text_field :optical_bandwidth %>
  </div>

  <div class="field">
    <%= form.label :coupling_coefficient %>
    <%= form.text_field :coupling_coefficient %>
  </div>

  <div class="field">
    <%= form.label :electric_Rx_bandwidth %>
    <%= form.text_field :electric_Rx_bandwidth %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/buses/edit.html.erb
<h1>Editing Bus</h1>

<%= render 'form', bus: @bus %>

<%= link_to 'Show', @bus %> |
<%= link_to 'Back', buses_path %>

app/views/buses/index.html.erb
<section class="content">
 
<p id="notice"><%= notice %></p>
<div class="box">
<div class="box-header with-border">
<h3 class="box-title">Buses</h3>
</div>
<!-- /.box-header -->
<div class="box-body">
<table class="table table-bordered">
 <thead>
   <tr>
     <th>Maximum transmission power</th>
     <th>Baud rate</th>
     <th>Receiver sensitivity</th>
     <th>Effective receiver band</th>
     <th>Codification</th>
     <th>Link distance</th>
     <th>Number of stations</th>
     <th>Insertion loss</th>
     <th>Loss of dp coupling</th>
     <th>Loss of excess dp</th>
     <th>Link length</th>     
     <th>Fiber attenuation coefficient</th>
     <th colspan="3"></th>
   </tr>
 </thead>

 <tbody>
   <% @buses.each do |bus| %>
     <tr>
       <td><%= bus.maximum_transmission_power %></td>
       <td><%= bus.baud_rate %></td>
       <td><%= bus.receiver_sensitivity %></td>
       <td><%= bus.effective_receiver_band %></td>
       <td><%= bus.codification %></td>
       <td><%= bus.link_distance %></td>
       <td><%= bus.number_of_stations %></td>
       <td><%= bus.insertion_loss %></td>
       <td><%= bus.loss_of_DP_coupling %></td>
       <td><%= bus.loss_of_excess_DP %></td>
       <td><%= bus.link_length %></td>
       <td><%= bus.fiber_attenuation_coefficient %></td>
     </tr>
   <% end %>
 </tbody>

  <thead>
    <tr> 
     <th>Loss of transmission of the t coupler</th>
     <th>Loss of coupling t coupler</th>
     <th>Excess loss of t coupler</th>
     <th>Dispersion balance</th>
     <th>Electric tx bandwidth</th>
     <th>Spectral width</th>
     <th>Chromatic dispersion</th>
     <th>Optical bandwidth</th>
     <th>Coupling coefficient</th>
     <th>Electric rx bandwidth</th>
     <th>Power Balance</th>
     <th colspan="3"></th>
   </tr>
 </thead>
 



 <tbody>
   <% @buses.each do |bus| %>
      <tr>
       <td><%= bus.loss_of_transmission_of_the_T_coupler %></td>
       <td><%= bus.loss_of_coupling_T_coupler %></td>
       <td><%= bus.excess_loss_of_T_coupler %></td>
       <td><%= bus.dispersion_balance %></td>
       <td><%= bus.electric_Tx_bandwidth %></td>
       <td><%= bus.spectral_width %></td>
       <td><%= bus.chromatic_dispersion %></td>
       <td><%= bus.optical_bandwidth %></td>
       <td><%= bus.coupling_coefficient %></td>
       <td><%= bus.electric_Rx_bandwidth %></td>
       <td><%= bus.power_balance %></td>
       <td><%= link_to 'Show', bus %></td>
       <td><%= link_to 'Edit', edit_bus_path(bus) %></td>
       <td><%= link_to 'Destroy', bus, method: :delete, data: { confirm: 'Are you sure?' } %></td>
     </tr>
   <% end %>
 </tbody>
</table>
 
</div>
</div>
 
<br>
 
<a class="btn btn-primary" style="color: white;" href="/buses/new">New Bus</a>
 
 </section>

app/views/buses/new.html.erb
<h1>New Bus</h1>

<%= render 'form', bus: @bus %>

<%= link_to 'Back', buses_path %>

app/views/buses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Maximum transmission power:</strong>
  <%= @bus.maximum_transmission_power %>
</p>

<p>
  <strong>Baud rate:</strong>
  <%= @bus.baud_rate %>
</p>

<p>
  <strong>Receiver sensitivity:</strong>
  <%= @bus.receiver_sensitivity %>
</p>

<p>
  <strong>Effective receiver band:</strong>
  <%= @bus.effective_receiver_band %>
</p>

<p>
  <strong>Codification:</strong>
  <%= @bus.codification %>
</p>

<p>
  <strong>Link distance:</strong>
  <%= @bus.link_distance %>
</p>

<p>
  <strong>Number of stations:</strong>
  <%= @bus.number_of_stations %>
</p>

<p>
  <strong>Insertion loss:</strong>
  <%= @bus.insertion_loss %>
</p>

<p>
  <strong>Loss of dp coupling:</strong>
  <%= @bus.loss_of_DP_coupling %>
</p>

<p>
  <strong>Loss of excess dp:</strong>
  <%= @bus.loss_of_excess_DP %>
</p>

<p>
  <strong>Link length:</strong>
  <%= @bus.link_length %>
</p>

<p>
  <strong>Fiber attenuation coefficient:</strong>
  <%= @bus.fiber_attenuation_coefficient %>
</p>

<p>
  <strong>Loss of transmission of the t coupler:</strong>
  <%= @bus.loss_of_transmission_of_the_T_coupler %>
</p>

<p>
  <strong>Loss of coupling t coupler:</strong>
  <%= @bus.loss_of_coupling_T_coupler %>
</p>

<p>
  <strong>Excess loss of t coupler:</strong>
  <%= @bus.excess_loss_of_T_coupler %>
</p>

<p>
  <strong>Dispersion balance:</strong>
  <%= @bus.dispersion_balance %>
</p>

<p>
  <strong>Electric tx bandwidth:</strong>
  <%= @bus.electric_Tx_bandwidth %>
</p>

<p>
  <strong>Spectral width:</strong>
  <%= @bus.spectral_width %>
</p>

<p>
  <strong>Chromatic dispersion:</strong>
  <%= @bus.chromatic_dispersion %>
</p>

<p>
  <strong>Optical bandwidth:</strong>
  <%= @bus.optical_bandwidth %>
</p>

<p>
  <strong>Coupling coefficient:</strong>
  <%= @bus.coupling_coefficient %>
</p>

<p>
  <strong>Electric rx bandwidth:</strong>
  <%= @bus.electric_Rx_bandwidth %>
</p>

<%= link_to 'Edit', edit_bus_path(@bus) %> |
<%= link_to 'Back', buses_path %>

app/views/home/index.html.erb
<h1>Bem vindo a versão web do Software Educacional de Redes Ópticas</h1>

app/views/layouts/_admin_lte_2_header.html.erb
<!-- Main Header -->
<header class="main-header">

  <!-- Logo -->
  <a href="/" class="logo">
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg">Software Educacional</span>
  </a>

  <!-- Header Navbar -->
  <nav class="navbar navbar-static-top" role="navigation">
  <!-- Menu Footer-->
  <div class="pull-right">
  <ul class="nav navbar-nav">
  <li>
    <a rel="nofollow" data-method="delete" href="/students/sign_out">
    <i class="fa fa-sign-out"></i>
    </a>
  </li>
  </ul>
  </a>        
  </div>
  </nav>
</header>

app/views/layouts/_admin_lte_2_sidebar.html.erb
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar Menu -->
    <ul class="sidebar-menu">
      <li class="header">MENU</li>
        <!-- Optionally, you can add icons to the links -->
      <li><a href="/rings">Anel</a></li>
      <li><a href="/buses">Barramento</a></li>
    </ul><!-- /.sidebar-menu -->
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/admin_lte_2.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Software Redes Ópticas</title>
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
  <link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>

<body class="skin-blue sidebar-mini fixed <%= params[:controller].parameterize %> <%= action_name %>">
  <div class="wrapper">

    <%= render partial: 'layouts/admin_lte_2_header' %>

    <%= render partial: 'layouts/admin_lte_2_sidebar' %>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Main content -->
      <section class="content">
        <% if notice %>
          <div class="alert alert-success alert-dismissable">
            <i class="fa fa-check"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <b><%= notice %></b>
          </div>
        <% end %>

        <% if alert %>
          <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <b><%= alert %></b>
          </div>
        <% end %>
        <%= yield %>
      </section><!-- /.content -->
    </div><!-- /.content-wrapper -->

    <!-- Main Footer -->
    <footer class="main-footer">
      <!-- To the right -->
      <div class="pull-right hidden-xs">
      Feito com ❤ por Rebeca Albuquerque
      </div>
      <!-- Default to the left -->
      <strong>Copyright &copy; 2021 <a href="#">Software Redes Ópticas</a>.</strong> All rights reserved.
    </footer>

    <aside class="control-sidebar control-sidebar-dark">
        <!-- Create the tabs -->
        <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
          <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab" aria-expanded="true"><i class="fa fa-home"></i></a></li>
          <li class=""><a href="#control-sidebar-settings-tab" data-toggle="tab" aria-expanded="false"><i class="fa fa-gears"></i></a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
          <!-- Home tab content -->
          <div class="tab-pane active" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class="control-sidebar-menu">
              <li>
                <a href="javascript::;">
                  <i class="menu-icon fa fa-birthday-cake bg-red"></i>
                  <div class="menu-info">
                    <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>
                    <p>Will be 23 on April 24th</p>
                  </div>
                </a>
              </li>
            </ul><!-- /.control-sidebar-menu -->

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class="control-sidebar-menu">
              <li>
                <a href="javascript::;">
                  <h4 class="control-sidebar-subheading">
                    Custom Template Design
                    <span class="label label-danger pull-right">70%</span>
                  </h4>
                  <div class="progress progress-xxs">
                    <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                  </div>
                </a>
              </li>
            </ul><!-- /.control-sidebar-menu -->

          </div><!-- /.tab-pane -->
          <!-- Stats tab content -->
          <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div><!-- /.tab-pane -->
          <!-- Settings tab content -->
          <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
              <h3 class="control-sidebar-heading">General Settings</h3>
              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Report panel usage
                  <input type="checkbox" class="pull-right" checked="">
                </label>
                <p>
                  Some information about this general settings option
                </p>
              </div><!-- /.form-group -->
            </form>
          </div><!-- /.tab-pane -->
        </div>
      </aside>

      <div class="control-sidebar-bg" style="position: fixed; height: auto;"></div>

  </div><!-- ./wrapper -->

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/layouts/admin_lte_2_login.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Software | Redes Ópticas</title>
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body class="login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="/"><b>Software</b> Redes Ópticas</a>
  </div><!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Sign in to start your session</p>
    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <div class="form-group has-feedback">
        <%= f.text_field :email, class: 'form-control', autofocus: true %>
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>

      <div class="form-group has-feedback">
        <%= f.password_field :password, class: 'form-control', autocomplete: 'off' %>
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
        </div><!-- /.col -->
        <div class="col-xs-4">
          <%= f.submit 'Log in', class: 'btn btn-primary btn-block btn-flat' %>

        </div><!-- /.col -->
      </div>

      <a href="/students/password/new">Forgot your password?</a>
    <% end %>
  </div><!-- /.login-box-body -->
</div><!-- /.login-box -->

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SoftwareRedesOpticas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rings/_form.html.erb
<%= form_with(model: ring, local: true) do |form| %>
  <% if ring.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ring.errors.count, "error") %> prohibited this ring from being saved:</h2>

      <ul>
      <% ring.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :maximum_transmission_power %>
    <%= form.text_field :maximum_transmission_power %>
  </div>

  <div class="field">
    <%= form.label :baud_rate %>
    <%= form.text_field :baud_rate %>
  </div>

  <div class="field">
    <%= form.label :receiver_sensitivity %>
    <%= form.text_field :receiver_sensitivity %>
  </div>

  <div class="field">
    <%= form.label :effective_receiver_band %>
    <%= form.text_field :effective_receiver_band %>
  </div>

  <div class="field">
    <%= form.label :codification %>
    <%= form.check_box :codification %>
  </div>

  <div class="field">
    <%= form.label :link_distance %>
    <%= form.check_box :link_distance %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rings/edit.html.erb
<h1>Editing Ring</h1>

<%= render 'form', ring: @ring %>

<%= link_to 'Show', @ring %> |
<%= link_to 'Back', rings_path %>

app/views/rings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rings</h1>

<table>
  <thead>
    <tr>
      <th>Maximum transmission power</th>
      <th>Baud rate</th>
      <th>Receiver sensitivity</th>
      <th>Effective receiver band</th>
      <th>Codification</th>
      <th>Link distance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rings.each do |ring| %>
      <tr>
        <td><%= ring.maximum_transmission_power %></td>
        <td><%= ring.baud_rate %></td>
        <td><%= ring.receiver_sensitivity %></td>
        <td><%= ring.effective_receiver_band %></td>
        <td><%= ring.codification %></td>
        <td><%= ring.link_distance %></td>
        <td><%= link_to 'Show', ring %></td>
        <td><%= link_to 'Edit', edit_ring_path(ring) %></td>
        <td><%= link_to 'Destroy', ring, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ring', new_ring_path %>

app/views/rings/new.html.erb
<h1>New Ring</h1>

<%= render 'form', ring: @ring %>

<%= link_to 'Back', rings_path %>

app/views/rings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Maximum transmission power:</strong>
  <%= @ring.maximum_transmission_power %>
</p>

<p>
  <strong>Baud rate:</strong>
  <%= @ring.baud_rate %>
</p>

<p>
  <strong>Receiver sensitivity:</strong>
  <%= @ring.receiver_sensitivity %>
</p>

<p>
  <strong>Effective receiver band:</strong>
  <%= @ring.effective_receiver_band %>
</p>

<p>
  <strong>Codification:</strong>
  <%= @ring.codification %>
</p>

<p>
  <strong>Link distance:</strong>
  <%= @ring.link_distance %>
</p>

<%= link_to 'Edit', edit_ring_path(@ring) %> |
<%= link_to 'Back', rings_path %>